name: CartOn
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.22.5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  dio: ^4.0.0-beta7
  shared_preferences: 2.0.1
  salomon_bottom_bar: ^2.0.0
  ionicons: ^0.0.3
  flutter_custom_clippers: ^1.1.2
  geolocator: ^7.0.1
#  permission_handler: ^4.4.0+hotfix.2
  geocoding: ^2.0.0
  location_permissions: ^3.0.0
  flutter_spinkit: "^4.1.2"
  flutter_svg: ^0.19.3
  flutter_linkify: ^5.0.0
  url_launcher: ^6.0.2
#  google_map_location_picker: ^4.1.7
  location: ^4.1.1
#  mapbox_gl: ^0.9.0
  flutter_map: ^0.11.0
  latlng: ^0.1.0
  avatar_glow: ^2.0.0
#  animating_location_pin: ^0.1.0
#  grouped_list: ^3.7.1
#  scrollable_list_tabview: ^0.1.6
  supercharged: ^2.0.0
#  toggle_bar: ^1.0.0
#  bubble_tab_indicator: "^0.1.4"
  scrollable_positioned_list: ^0.1.8
  provider: ^5.0.0
  google_nav_bar: ^3.1.0
  badges: ^1.1.6
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.8.1
  razorpay_flutter: ^1.2.5
  fluttertoast: ^7.1.6
  flutter_secure_storage: 3.3.3
  circular_check_box: ^1.0.4
  flushbar: ^1.10.4
  recase: ^3.0.1
  flutter_advanced_switch: ^0.0.9+3
  sliding_switch: ^0.0.3
  confetti: ^0.5.4+1
  timeline_tile: ^1.0.0
  intl: ^0.17.0
  timelines: ^0.0.2+1
  emojis: ^0.9.3
  im_animations: ^0.1.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/svg/orderStatus/
    - assets/images/main_items/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    - family: OxygenRegular
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf

    - family: OxygenBold
      fonts:
        - asset: assets/fonts/Oxygen-Bold.ttf

    - family: OxygenLight
      fonts:
        - asset: assets/fonts/Oxygen-Light.ttf

    - family: QuicksandRegular
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf

    - family: QuicksandBold
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf

    - family: QuicksandMedium
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf

    - family: QuicksandSemiBold
      fonts:
        - asset: assets/fonts/Quicksand-SemiBold.ttf

    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  ios: true
  android: true
  image_path: "assets/launcher/icon.png"
